### ISSUE TITLE
Generated File missing end of Expression

### ISSUE THREAD

**Issue by captDaylight** [prisma/prisma1#4575]
When generating my files I’m getting this error:
```bash
▸    ';' expected. (176:8)
▸    174 | export type ShortCodeTxJarsOrderByInput =
▸    175 |
▸    > 176 | export type UserOrderByInput =   'id_ASC' |
▸    |        ^
```
So it looks like `ShortCodeTxJarsOrderByInput` is not getting assigned a variable. Here is an abbreviated schema:

```graphql
type ShortCodeTx {
  id: ID! @id
  jars: [Jar!]! @relation(link: TABLE, name: "ShortCodeTxJars")
  updatedAt: DateTime! @updatedAt
  createdAt: DateTime! @createdAt
}

type ShortCodeTxJars @relationTable {
  jar: Jar!
  shortCodeTx: ShortCodeTx!
}

type Jar {
  id: ID! @id
  transactions: [ShortCodeTx!]! @relation(name: "ShortCodeTxJars")
  updatedAt: DateTime! @updatedAt
  createdAt: DateTime! @createdAt
}
```

Referenced from this post on the [forum](https://www.prisma.io/forum/t/generated-file-missing-end-of-expression/7059).

**Comment by pantharshit00** [comment]
This bug has already been reported. https://github.com/prisma/prisma/issues/4424

This has been fixed in 1.33 so please try that version.

I am no longer able to reproduce this.

![Uploading image.png…]()

**Comment by jvaca92** [comment]
Actually I am struggling with the same error nowadays . As I can see this bug should be fixed in version 1.33 but I have used 1.34.1 and the error is still happened.

```
SyntaxError: ';' expected. (142:8)
  140 | export type SheetPermissionOrderByInput =
  141 | 
> 142 | export type WorkbookOrderByInput =   'workbook_id_ASC' |
      |        ^
  143 |   'workbook_id_DESC' |
  144 |   'created_ASC' |
  145 |   'created_DESC' | 
```

Prisma schema

```
type Sheet @db(name: "sheet") {
  sheet_id: Int! @id
  active: Boolean
  cell: [Cell]
  created: DateTime
  isSynchronized: Boolean @db(name: "is_synchronized")
  mappedSheetId: Int @db(name: "mapped_sheet_id")
  name: String
  sheetPermission: [SheetPermission]
  synchronizationType: SynchronizationType! @db(name: "synchronization_type_id")
  workbook: Workbook! @db(name: "workbook_id")
}

type SheetPermission @db(name: "sheet_permission") @relationTable {
  sheet: Sheet! @db(name: "sheet_id")
  user: User! @db(name: "user_id")
}

type User @db(name: "user") {
  user_id: Int! @id
  created: DateTime
  name: String
  sheetPermission: [SheetPermission]
  workbook: [Workbook]
}
```
